version: '3'

services:
  web:
    build: .
    command: node dist/main.js
    ports:
      - "3000:3000"

  nodejs_worker:
    build: .
    #volumes:
    #  - /mnt/volume_fra1_01:/storage1
    command: node dist/crawler.main.js

  python_worker:
    build: ./workers

  frontend:
    build: ./frontend
    ports:
      - "3030:80"
    depends_on:
      - web

  widget:
    build: ./widget
    ports:
      - "3031:80"
    depends_on:
      - web

  nginx:
    image: nginx
    volumes:
      - web-root:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./dhparam/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - frontend
      - widget

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email soeren@blauedaecher.com --agree-tos --no-eff-email --force-renewal -d app.digitalerguide.com -d api.digitalerguide.com -d widget.digitalerguide.com

volumes:
  certbot-etc:
  certbot-var:
  web-root: