version: '3'

services:
  web:
    build: .
    command: node dist/main.js
    ports:
      - "3000:3000"

  nodejs_worker:
    build: .
    volumes:
      - /mnt/volume_fra1_01:/storage1
    command: node dist/crawler.main.js

  python_worker:
    build: ./workers

  frontend:
    build: ./frontend
    ports:
      - "3030:80"
    depends_on:
      - web

  widget:
    build: ./widget
    ports:
      - "3031:80"
    depends_on:
      - web